Milestone5
vidhishweta01/react_calculator pull request #6
Opened 2021-08-21 12:41 UTC by vidhishweta01

Added clickHandler to app, button panel, button
logic is now connected to UI of the calculator 
I

2021-08-21 13:45 UTC, george-shammar requested changes
Hi @vidhishweta01 , 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-21 13:45 UTC, george-shammar commented on src/component/App/App.js
> +      <>
- [ ] Please, always remember to make your commits in the present imperative tenses. You have committed your codes in past tense. 
- [ ] Please, do not disable eslint as you did here on line 12. There's a simple work around for this eslint error. Please, let's fix it. :pray: 
- [ ] I got this error `Error: [big.js] Division by zero` when i tried to divide a number by zero. Please, let's handle this exception.

2021-08-22 12:05 UTC, taiwo2 requested changes
@vidhishweta01 Nice job done on the suggested changes, I can't find the requested changes but however, few changes are required to get your project approved
### highlights
Git flow 👍🏻 
### Improve 

- [ ] button `%` still not working. kindly fix 
- [ ] your division by 0 should display `Division by Zero error` not  ` something went wrong` so that the user can know that it's an error.

### once specific changes are made kindly request for another review

2021-08-22 13:07 UTC, vidhishweta01 commented
https://www.loom.com/share/fe3dfde4691942c186f4a50e84d5d1ca

2021-08-22 13:49 UTC, rindrajosia approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-08-22 13:49 UTC, rindrajosia commented on src/logic/calculate.js
> +  // }
- [ ]  [OPTIONAL] Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-08-22 13:49 UTC, rindrajosia commented on src/logic/operate.js
> -    return ONE.mod(TWO).toString();
- [ ]  [OPTIONAL] In fact, this operator should return percentage, not modulo. 
![1](https://user-images.githubusercontent.com/58552748/130351133-fd843b0d-05d0-40a7-a45d-ed8e32092d2f.png)

2021-08-22 19:36 UTC, merged